In [3]:
import tushare as ts

df = ts.get_hist_data('600848') #一次性获取全部数据

In [9]:
df['open']

date
2018-11-23    23.70
2018-11-22    23.46
2018-11-21    22.70
2018-11-20    22.00
2018-11-19    23.40
2018-11-16    21.46
2018-11-15    20.76
2018-11-14    20.10
2018-11-13    19.89
2018-11-12    20.12
2018-11-09    20.32
2018-11-08    20.58
2018-11-07    21.70
2018-11-06    19.35
2018-11-05    18.30
2018-11-02    17.70
2018-11-01    17.83
2018-10-31    17.13
2018-10-30    17.25
2018-10-29    17.02
2018-10-26    17.65
2018-10-25    16.54
2018-10-24    16.67
2018-10-23    16.94
2018-10-22    16.18
2018-10-19    14.76
2018-10-18    16.10
2018-10-17    17.00
2018-10-16    17.90
2018-10-15    17.83
              ...
2016-08-16    21.81
2016-08-15    21.60
2016-08-12    20.77
2016-08-11    21.09
2016-08-10    21.44
2016-08-09    21.14
2016-08-08    21.41
2016-08-05    22.15
2016-08-04    21.79
2016-08-03    21.00
2016-08-02    20.55
2016-08-01    20.37
2016-07-29    20.92
2016-07-28    21.98
2016-07-27    21.82
2016-07-26    22.15
2016-07-25    20.17
2016-07-22    19.41
2016-07-21    18.31
2016-07-20    18.17
2016-07-19    18.30
2016-07-18    18.00
2016-07-15    17.69
2016-07-14    17.60
2016-07-13    17.88
2016-07-12    17.82
2016-07-11    18.00
2016-07-08    19.50
2016-07-07    18.66
2016-07-06    16.96
Name: open, Length: 499, dtype: float64